In [2]:
import pickle
import numpy as np

In [4]:
ohe_sex = pickle.load(open('Models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('Models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('Models/clf.pkl','rb'))

In [10]:
#Assume input 
# pclass/gender/age/sibsp/parch/fare/Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [12]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [22]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

In [24]:
test_input_sex

array([[0., 1.]])

In [26]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [28]:
test_input_embarked

array([[0., 0., 1.]])

In [30]:
test_input_age = test_input[:,2].reshape(1,1)

In [32]:
test_input_age

array([[31.0]], dtype=object)

In [34]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [36]:
test_input_transformed.shape

(1, 10)

In [38]:
clf.predict(test_input_transformed)

array([1], dtype=int64)