In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [4]:
df = pd.read_csv('train (1).csv',usecols=['Age','Fare','Survived'])

In [6]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [8]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [10]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
x_train.head()

Age     Fare
331  45.5  28.5000
733  23.0  13.0000
382  32.0   7.9250
704  26.0   7.8542
813   6.0  31.2750

In [14]:
si = SimpleImputer()
x_train_trf = si.fit_transform(x_train)

In [22]:
x_test_trf = si.transform(x_test)

In [24]:
x_train_trf

array([[ 45.5   ,  28.5   ],
       [ 23.    ,  13.    ],
       [ 32.    ,   7.925 ],
       ...,
       [ 41.    ,  14.1083],
       [ 14.    , 120.    ],
       [ 21.    ,  77.2875]])

In [26]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(x_train_trf,y_train)
y_pred = clf.predict(x_test_trf)

In [28]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score(y_test,y_pred)

0.6480446927374302

In [32]:
mi = MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [34]:
mi.features_

array([0], dtype=int64)

In [36]:
x_train_missing = mi.transform(x_train)

In [38]:
x_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [40]:
x_test_missing = mi.transform(x_test)

In [42]:
x_test_missing

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [44]:
x_train['Age_na'] = x_train_missing

In [46]:
x_test

Age     Fare
709   NaN  15.2458
439  31.0  10.5000
840  20.0   7.9250
720   6.0  33.0000
39   14.0  11.2417
..    ...      ...
433  17.0   7.1250
773   NaN   7.2250
25   38.0  31.3875
84   17.0  10.5000
10    4.0  16.7000

[179 rows x 2 columns]

In [48]:
x_test['Age_na'] = x_test_missing

In [50]:
x_train

Age      Fare  Age_na
331  45.5   28.5000   False
733  23.0   13.0000   False
382  32.0    7.9250   False
704  26.0    7.8542   False
813   6.0   31.2750   False
..    ...       ...     ...
106  21.0    7.6500   False
270   NaN   31.0000    True
860  41.0   14.1083   False
435  14.0  120.0000   False
102  21.0   77.2875   False

[712 rows x 3 columns]

In [52]:
si = SimpleImputer()
x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [54]:
from sklearn.linear_model import LogisticRegression

In [56]:
clf = LogisticRegression()
clf.fit(x_train_trf2,y_train)
y_pred = clf.predict(x_test_trf2)

In [58]:
from sklearn.metrics import accuracy_score

In [60]:
accuracy_score(y_test,y_pred)

0.6368715083798883

# Missing Indicator with SimpleImputer 

In [63]:
si = SimpleImputer(add_indicator=True)

In [65]:
x_train = si.fit_transform(x_train)

In [67]:
x_test = si.transform(x_test)

In [69]:
from sklearn.linear_model import LogisticRegression

In [71]:
clf = LogisticRegression()
clf.fit(x_train_trf2,y_train)
y_pred = clf.predict(x_test_trf2)

In [73]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6368715083798883