In [1]:
import numpy as np

In [7]:
ar1 = np.arange(4)
ar2 = np.arange(20).reshape(5,4)

print(ar1)
print("\n")
print(ar2)

[0 1 2 3]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [11]:
ar1 + ar2  # Broadcasting make the lower dimension array as higher dimension array
            # as same value and perform the operation but atleast one dimension shall be
            # same with other array

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22]])

In [29]:
ar3 = np.arange(6).reshape(3,2)
ar4 = np.array([5,2])
print(ar3)
print("\n")
print(ar4)

[[0 1]
 [2 3]
 [4 5]]


[5 2]


In [25]:
ar3+ar4

array([[5, 3],
       [7, 5],
       [9, 7]])