In [2]:
import numpy as np

In [4]:
arr = np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[ 1, 14, 23, 37,  6],
       [96, 80, 76, 66, 48],
       [94, 84, 21, 15,  7],
       [63, 85, 24, 62, 64]])

In [6]:
# Indexing using Boolian array 
arr[arr>50]

array([96, 80, 76, 66, 94, 84, 63, 85, 62, 64])

In [8]:
arr>50

array([[False, False, False, False, False],
       [ True,  True,  True,  True, False],
       [ True,  True, False, False, False],
       [ True,  True, False,  True,  True]])

In [10]:
arr[(arr>50) & (arr%2!=0)]

array([63, 85])

In [12]:
arr[(arr>50) & (arr%2!=0)] = 0

In [14]:
arr

array([[ 1, 14, 23, 37,  6],
       [96, 80, 76, 66, 48],
       [94, 84, 21, 15,  7],
       [ 0,  0, 24, 62, 64]])