In [2]:
import numpy as np

In [6]:
np.random.random()

0.019016400002854206

In [10]:
# get constant value using seed
np.random.seed(42)
np.random.random()

0.3745401188473625

In [6]:
#  random float number in a given range
np.random.uniform(3,10)

7.4322728177501345

In [10]:
# n random float values
np.random.uniform(50,100,12).reshape(3,4) # here 12 random values range of 50 to 100
                                        # using reshape we can make matrix

array([[93.96495861, 75.80124952, 63.07286239, 68.69826623],
       [66.64820563, 71.31486144, 63.07442949, 61.48014569],
       [92.60752679, 63.55366223, 86.13688974, 52.82299173]])

In [12]:
# random int values
np.random.randint(1,15)

6

In [14]:
np.random.randint(3,18,8).reshape(4,2)

array([[13,  5],
       [15,  9],
       [12, 15],
       [ 9,  7]])

In [16]:
a = np.random.randint(1,10,6)

In [24]:
a

array([8, 4, 6, 7, 5, 2])

In [18]:
np.max(a)

8

In [20]:
np.mean(a)

5.333333333333333

In [28]:
np.argmax(a)

0

In [30]:
a[np.argmax(a)]

8

In [32]:
np.argmin(a)

5

In [34]:
a[np.argmin(a)]

2

In [36]:
b = np.random.randint(1,15,7)

In [38]:
b

array([11, 10,  5, 10,  5,  7,  7])

In [40]:
b[b%2==1]=-1

In [42]:
b

array([-1, 10, -1, 10, -1, -1, -1])

In [44]:
c = np.random.randint(5,50,8)
c

array([ 5, 22, 45,  9, 16, 26, 11, 35])

In [52]:
out = np.where(c%2==1,-1,c)
out

array([-1, 22, -1, -1, 16, 26, -1, -1])

In [48]:
c

array([ 5, 22, 45,  9, 16, 26, 11, 35])

In [54]:
 np.sort(c)

array([ 5,  9, 11, 16, 22, 26, 35, 45])

In [62]:
np.percentile(c,60)

22.8