In [2]:
import numpy as np

In [15]:
arr = np.array([1,2,3,4,5])

In [9]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Indexing

In [25]:
arr1[2]

array([ 8,  9, 10, 11])

# slicing

In [45]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [47]:
arr1[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [49]:
arr1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [57]:
arr1[-2:,-2:]

array([[18, 19],
       [22, 23]])

# Iteration

In [62]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [64]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
