In [2]:
import numpy as np

# vector operation

In [4]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [8]:
arr1-arr2 # position or element operation -->vertor subtraction

array([-3, -3, -3, -3, -3, -3])

In [10]:
arr1*arr2 # same as before  -->vector   multiplication

array([ 4, 10, 18, 28, 40, 54])

In [12]:
arr2 > 3

array([ True,  True,  True,  True,  True,  True])

In [14]:
arr1 > 3

array([False, False, False,  True,  True,  True])

In [21]:
# dot product
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
arr3,arr4

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [23]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [25]:
arr4.min()

6

In [27]:
arr4.max()

11

In [31]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [29]:
arr4.min(axis=0)

array([6, 7])

In [33]:
arr4.max(axis=1)

array([ 7,  9, 11])

In [35]:
arr4.sum(axis=0)

array([24, 27])

In [37]:
arr4.sum(axis=1)

array([13, 17, 21])

In [39]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [41]:
np.median(arr4)

8.5

In [43]:
arr4.mean()

8.5

In [45]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [47]:
np.log(arr4)

array([[1.79175947, 1.94591015],
       [2.07944154, 2.19722458],
       [2.30258509, 2.39789527]])

In [49]:
np.tan(arr1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619])