In [2]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr1.shape

(5,)

In [24]:
arr1.ndim

1

In [26]:
arr1.size

5

In [10]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr2.shape

(2, 3)

In [22]:
arr2.ndim

2

In [28]:
arr2.size

6

In [14]:
arr3d = np.array([[[1,2],[2,3]],[[5,6],[7,8]]])
arr3d

array([[[1, 2],
        [2, 3]],

       [[5, 6],
        [7, 8]]])

In [16]:
arr3d.shape

(2, 2, 2)

In [18]:
arr3d.ndim

3

In [30]:
arr3d.size

8

In [32]:
arr3d.itemsize

4

In [34]:
arr3d.dtype

dtype('int32')

In [38]:
arr3d.astype('float')

array([[[1., 2.],
        [2., 3.]],

       [[5., 6.],
        [7., 8.]]])

In [40]:
arr3d.itemsize

4

In [42]:
arr3d.dtype

dtype('int32')